### ISSUE TITLE
Application deletes wow6432node run key for local machine

### ISSUE THREAD

**Issue by Happygolucky254** [IgorMundstein/WinMemoryCleaner#18]
**Describe the bug**
This program deletes: HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Run

**To Reproduce**
1. Start the program.

**Expected behavior**
Wait for user input.

**Screenshots**
Not required.

**Desktop (please complete the following information):**
 - OS: Windows 7

**Additional context**
It took me a week to track this problem and writing a powershell script myself to monitor my registry key.
I had missing startup programs recently but I couldn't see where they were missing from by using tools like externals autoruns. Eventually purely by accident I discovered the following registry key was missing:

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Run

I managed to recover from a backup registry which had 13 startup programs.
Left my script running and got a result running this application.
Restored my key and retested.
Confirmed this program deletes startup programs in windows 7.
Have not tested other systems.
Unless fixed and ensured confidence in the programs activity, I will not be using this application.

**Comment by IgorMundstein** [comment]
@Happygolucky254 

Thanks for the bug report. Sorry for the behavior. It will be fixed in the next version.

**Comment by Happygolucky254** [comment]
Yeah, I assume the application is supposed to check the startup mode and or add or remove itself from startup depending on user configuration but there a incorrect "\" or string. It's just a little scary as it's virus like behavior but the fact you've already replied gave me every confidence it an error and will be fixed and at the time I could remember if it was open source. Thanks for your work and have a good day.

**Comment by IgorMundstein** [comment]
> Yeah, I assume the application is supposed to check the startup mode and or add or remove itself from startup depending on user configuration but there a incorrect "\\" or string somewhere. It's just a little scary as it's virus like behavior but the fact you've already replied gave me every confidence it an error and will be fixed and at the time I couldn't remember if it was open source. Thanks for your work and have a good day.

Yes. This is for startup logic. It is a simple open-source app that does the job without ads, installation, or pay-to-use. It's been maintained by one single developer. I am trying to improve it as per requests, but this is a non-profit project and I have other priorities in my hands. I'll launch an update this weekend. It will fix this bug. I hope you enjoy it. 👍

**Comment by IgorMundstein** [comment]
Fixed. 

Please, review the 2.1 version: https://github.com/IgorMundstein/WinMemoryCleaner/releases/tag/2.1

**Comment by HeyItsJono** [comment]
> **Describe the bug** This program deletes: HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Run
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Start the program.
> 
> **Expected behavior** Wait for user input.
> 
> **Screenshots** Not required.
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 7
> 
> **Additional context** It took me a week to track this problem and writing a powershell script myself to monitor my registry key. I had missing startup programs recently but I couldn't see where they were missing from by using tools like externals autoruns. Eventually purely by accident I discovered the following registry key was missing:
> 
> HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Run
> 
> I managed to recover from a backup registry which had 13 startup programs. Left my script running and got a result running this application. Restored my key and retested. Confirmed this program deletes startup programs in windows 7. Have not tested other systems. Unless fixed and ensured confidence in the programs activity, I will not be using this application.

Out of curiosity, what script did you write to track down the culprit program?

**Comment by Happygolucky254** [comment]
> > **Describe the bug** This program deletes: HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Run
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. Start the program.
> > 
> > **Expected behavior** Wait for user input.
> > **Screenshots** Not required.
> > **Desktop (please complete the following information):**
> > 
> > * OS: Windows 7
> > 
> > **Additional context** It took me a week to track this problem and writing a powershell script myself to monitor my registry key. I had missing startup programs recently but I couldn't see where they were missing from by using tools like externals autoruns. Eventually purely by accident I discovered the following registry key was missing:
> > HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Run
> > I managed to recover from a backup registry which had 13 startup programs. Left my script running and got a result running this application. Restored my key and retested. Confirmed this program deletes startup programs in windows 7. Have not tested other systems. Unless fixed and ensured confidence in the programs activity, I will not be using this application.
> 
> Out of curiosity, what script did you write to track down the culprit program?

I eventually go this to work, it doesn't pinpoint the process per se, but lets you know when a key disappears along with logged process but it was blatantly obvious when I launched the program. Programs that launch themselves  might be a little more tricky to hunt down in that case you can maybe use process hacker with the 30 second highlight for process start and exit and after you get the notification you'll be able to see what process stared and ended within the last 30 seconds as green or red.

`$regPath = "HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Run"

while($true) {
    if(!(Test-Path $regPath)) {
        # Log running processes
        Get-Process | Out-File "C:\Standalone\PSScripts\PSMonitorRunKey\processes.log"

        Write-Host "Registry key not found. Playing sound, showing message, and logging processes..."
        # Play sound
        (New-Object Media.SoundPlayer "C:\Windows\Media\Windows Notify.wav").PlaySync()

        # Show message box
        $wshell = New-Object -ComObject Wscript.Shell
        $wshell.Popup("Registry key not found",0,"Alert",0x1)

        # Exit the script
        break
    } else {
        # Sleep for 1 second before polling again
        Start-Sleep -Seconds 1
    }
}`
