### ISSUE TITLE
Close to systray only works after minimizing to taskbar and restoring first

### ISSUE THREAD

**Issue by Girofox** [IgorMundstein/WinMemoryCleaner#19]
**Describe the bug**

While selecting the option 'Minimize to tray when closed' the window shrinks in the lower left corner as a contentless windows when clicking 'x' symbol. See the attached image for the effect.

**Steps to reproduce the behavior**
1. Go to "settings" and select option 'Minimize to tray when closed'
2. Click on 'x' symbol
3. Look at taskbar and desktop
4. Icon disappears from taskbar but there may be a contentless window on desktop

**Expected behavior**
Window should close without trace and there should not be a taskbar symbol when clicking 'x' symbol while option 'Minimize to tray when closed' is select.

**Screenshots**
![image](https://github.com/IgorMundstein/WinMemoryCleaner/assets/43116061/052ceb4e-8c6b-486d-ae06-d6bc12e5be15)

**Desktop**
 - OS: Windows 11 22H2 (Build 22621.1848)

**Additional context**

Possible workaround that works for me and may help finding cause of bug:

_Minimize window to taskbar -> Restore window from taskbar -> Choose "x" symbol to minimize to tray_

**Comment by IgorMundstein** [comment]
Fixed. 

Please, review the 2.1 version: https://github.com/IgorMundstein/WinMemoryCleaner/releases/tag/2.1
