### ISSUE TITLE
Command switches

### ISSUE THREAD

**Issue by truefriend-cz** [IgorMundstein/WinMemoryCleaner#2]
Hello, do you can add to this app support for command switches? For silent running

Example WinMemoryCleaner.exe /aa /bb /cc

**Comment by IgorMundstein** [comment]
Sure, I will do it.

**Comment by IgorMundstein** [comment]
Done.

![image](https://user-images.githubusercontent.com/3512138/132146365-1db95b39-89fc-4197-b916-103793918c4f.png)

**Comment by truefriend-cz** [comment]
Thank you very much! Great aplication! Great developer!
