### ISSUE TITLE
"Hotkey is already registered"

### ISSUE THREAD

**Issue by uhlease** [IgorMundstein/WinMemoryCleaner#30]
When first starting WinMemoryCleaner, a popup will appear stating "Hotkey is already registered"
... I never even attempted to register any sort of hotkey ever. So, how do I get this message to stop greeting me upon Startup?
![StartUpMsg](https://github.com/IgorMundstein/WinMemoryCleaner/assets/81602546/9e4a3022-393a-4690-877d-85b855ea5a1c)

**Comment by IgorMundstein** [comment]
Version 2.1 has a hotkey `Ctrl + Alt + M` set to optimize.

It will be customizable as a setting on the next update (2.2), and this message will disappear.

**Comment by IgorMundstein** [comment]
Fixed on release [2.2](https://github.com/IgorMundstein/WinMemoryCleaner/releases/tag/2.2)
