### ISSUE TITLE
i can't open the GUI

### ISSUE THREAD

**Issue by TheRobotHacker** [IgorMundstein/WinMemoryCleaner#49]
### Checklist

- [X] I have used the search function to see if someone else has submitted the same bug report.
- [X] I will describe the problem in as much detail as possible.

### App version

2.5.0.0

### Windows version

Windows 10

### Steps To Reproduce

i don't really know how to reproduce it, i just downloaded the file and tried to run the .exe

### Current Behavior

after running the .exe (i tried to run as administrator too) i get a notification that says "Hotkey (Alt, Control, M) is in use by Windows" but when i try to press the keys, nothing shows up
![image](https://github.com/IgorMundstein/WinMemoryCleaner/assets/134932311/4053e626-43f4-48b4-b159-035db3de209e)

### Expected Behavior

as far as I understand it should open the GUI, but it does not

**Comment by IgorMundstein** [comment]
The app is probably already open. Check the system tray icon. You can kill the process and try to re-open it. An icon should appear in the notification area. Double-click it. The process could have stuck during an update.

**Comment by TheRobotHacker** [comment]
thank you, now it works
