### ISSUE TITLE
More specific auto optimisation timing interval

### ISSUE THREAD

**Issue by AetherYT** [IgorMundstein/WinMemoryCleaner#52]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem in as much detail as possible.
- [X] This issue only requests one feature, **not** multiple (related) features.

### App version

2.5

### Problem you are trying to solve

I would like to have a custom interval instead of in hours, something like every 10 minutes or such. I am unable to do it manually without recompiling as DWORD 32-bit keys only support integers and no float values. This is mostly for convenience, but I hope you still consider it, it will be greatly appreciated!

### Suggested solution

```
if (DateTimeOffset.Now.Subtract(_lastAutoUpdate).TotalHours < Constants.App.AutoUpdateInterval)
                    return;
```
I believe replacing TotalHours function with TotalMinutes would save the DWORD as a minute value registry key, allowing the interval value to be in minutes.

### Screenshots / Drawings / Technical details

Make the interval value a text input field instead of a slider :)

**Comment by IgorMundstein** [comment]
Constants.App.AutoUpdateInterval is the interval to check for updates.
Settings.AutoOptimizationInterval is the variable that holds what you are looking for.

You won't be able to change it by editing manually the registry. 

![image](https://github.com/IgorMundstein/WinMemoryCleaner/assets/3512138/af560b64-0eb5-4a21-a481-823ca4673e7a)

 It's not recommended to run it every X minutes. That's why the setting is in hours.

Sorry, but there are no plans to change it.

**Comment by AetherYT** [comment]
Oh, thanks for the reply, and for pointing out my mistake :D Thank you for the great app! May I know why it is not recommended to run it every X minutes? I'm not very knowledga

**Comment by IgorMundstein** [comment]
No worries.

When you optimize memory areas, Windows will re-allocate what it thinks needs re-allocation, but not everything as before. This process has a cost and can take seconds to minutes, depending on each computer's hardware. Windows generally manages memory very well.  The biggest problem I've seen is in applications and games that allocate too much memory and don't clean it up. Auto-optimization by % free memory is more recommended. Optimizing every X time can often even slow down the system. Therefore, the recommended minimum is 1 hour. I could even change this to minutes, but I don't recommend it. Currently, if you configure 100% auto optimization by percentage, it will run every 5 minutes, as you will never be able to reach 100% free memory. Feel free to test this option.

**Comment by AetherYT** [comment]
Thank you for your response!
