### ISSUE TITLE
stuck at minimized

### ISSUE THREAD

**Issue by markperezone** [IgorMundstein/WinMemoryCleaner#59]
### Checklist

- [x] I have used the search function to see if someone else has submitted the same bug report.
- [X] I will describe the problem in as much detail as possible.

### App version

latest

### Windows version

windows 10

### Steps To Reproduce

1. opening

### Current Behavior

Cannot open any settings page

### Expected Behavior

I need a button for settings page at taskbar icon

**Comment by IgorMundstein** [comment]
Please verify the Windows system tray/notification area. There must be an icon you can click to open/hide the app.

**Comment by markperezone** [comment]
i click from notification but nothing opening. i was choose minimized and still cannot access to main menu.

**Comment by IgorMundstein** [comment]
I couldn't reproduce it.

Make sure you have the latest version (2.5): https://github.com/IgorMundstein/WinMemoryCleaner/releases/download/2.5/WinMemoryCleaner.exe

Things to try

- You can try killing the process in Task Manager and re-open the app.
- You can check for errors in Windows Event Viewer. Search for Windows Memory Cleaner as a Source.
- You can delete the Computer\HKEY_CURRENT_USER\Software\WinMemoryCleaner keys in the registry. So, the app will restart the settings to default when you open it again.

**Comment by IgorMundstein** [comment]
A similar issue reported on #62 

Improved on version [2.6](https://github.com/IgorMundstein/WinMemoryCleaner/releases/tag/2.6)
