### ISSUE TITLE
Add virtual memory display

### ISSUE THREAD

**Issue by Arvinsyt** [IgorMundstein/WinMemoryCleaner#60]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem in as much detail as possible.
- [x] This issue only requests one feature, **not** multiple (related) features.

### App version

2.5

### Problem you are trying to solve

Is it feasible to include virtual memory usage information on the main interface, similar to the functionality seen in [Memreduct](https://github.com/henrypp/memreduct).Thank you!

### Suggested solution

Similar to the functionality provided by [Memreduct](https://github.com/henrypp/memreduct).

**Comment by IgorMundstein** [comment]
I chose not to include it to keep the UI cleaner. I'll keep in mind the suggestion.

BTW. For deep memory analysis, I recommended RAMMap: https://learn.microsoft.com/en-us/sysinternals/downloads/rammap

**Comment by IgorMundstein** [comment]
Added to version [2.6](https://github.com/IgorMundstein/WinMemoryCleaner/releases/tag/2.6)
