### ISSUE TITLE
kmode_exception_not_handled BSOD

### ISSUE THREAD

**Issue by LeDeliJelly** [IgorMundstein/WinMemoryCleaner#61]
### Checklist

- [X] I have used the search function to see if someone else has submitted the same bug report.
- [X] I will describe the problem in as much detail as possible.

### App version

2.5

### Windows version

22H2 OS Build 19045.3693

### Steps To Reproduce

idk just optimizing a lot

### Current Behavior

windows bsod

### Expected Behavior

no bsod

### Anything else?

why are there so many requried questions feels like homework 💀

**Comment by IgorMundstein** [comment]
Have you spammed the Optimize button? 😅

It seems it doesn't happen immediately. I recommend you don't optimize all the time. If you are facing some issues, the reason might not be memory.
