### ISSUE TITLE
Win11上显示错误

### ISSUE THREAD

**Issue by Fgaoxing** [IgorMundstein/WinMemoryCleaner#65]
### Checklist

- [X] I have used the search function to see if someone else has submitted the same bug report.
- [X] I will describe the problem in as much detail as possible.

### App version

latest

### Windows version

11

### Steps To Reproduce

1. 
![image](https://github.com/IgorMundstein/WinMemoryCleaner/assets/92655031/620a462d-b81e-4adf-9403-803ae243a74b)

### Current Behavior

![image](https://github.com/IgorMundstein/WinMemoryCleaner/assets/92655031/707c6935-aaba-40d2-b8bb-4a1a29b53cb1)

**Comment by IgorMundstein** [comment]
This feature is challenging because the app needs to create a real-time icon. I need more info about your machine/system.

What's your resolution?

**Comment by IgorMundstein** [comment]
Improved on version [2.7](https://github.com/IgorMundstein/WinMemoryCleaner/releases/tag/2.7)
