### ISSUE TITLE
WinMemoryCleaner blocked by Windows Defender

### ISSUE THREAD

**Issue by strawberryaika** [IgorMundstein/WinMemoryCleaner#67]
### Checklist

- [X] I have used the search function to see if someone else has submitted the same bug report.
- [X] I will describe the problem in as much detail as possible.

### App version

Latest

### Windows version

Windows 10

### Steps To Reproduce

I reinstalled the software multiple times even through different sites but it detects a virus (trojan)

### Current Behavior

Cannot download/run WinMemoryCleaner

### Expected Behavior

The program should run with no issues.

**Comment by DJEX93** [comment]
+1

**Comment by IgorMundstein** [comment]
### That's a common issue that persists every time a new app version is released. I constantly submit the executable to Microsoft. Usually, it takes 24 hours to 48 hours for Microsoft to remove the detection.

Meanwhile, you can follow this procedure.
https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

The app adds entries to the registry and task scheduler to run the app on startup. Windows doesn't "like" apps with admin privileges running on startup. I get that, but this is the way to do it. I apologize, but the app can not deep clean the memory without admin privileges.

It helps if more users submit the app to Microsoft analysis.
https://www.microsoft.com/en-us/wdsi/filesubmission

![Untitled](https://github.com/IgorMundstein/WinMemoryCleaner/assets/3512138/63cc4a50-6b2f-4b0b-88d2-7f5a7a106630)

### Microsoft feedback e-mail

> At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.
> 
> Open the command prompt as administrator.
> 
> 1. cd "c:\Program Files\Windows Defender"
> 2. MpCmdRun.exe -removedefinitions -dynamicsignatures
> 3. MpCmdRun.exe -SignatureUpdate

![image](https://github.com/IgorMundstein/WinMemoryCleaner/assets/3512138/bfb35128-9868-48e0-9f79-96619695a455)

### Similar reports

- [Bitdefender Flagged and Removed the .exe](https://github.com/IgorMundstein/WinMemoryCleaner/issues/48)
- [Flagged as malware by Windows](https://github.com/IgorMundstein/WinMemoryCleaner/discussions/45)

**Comment by IgorMundstein** [comment]
Added to [Frequently Asked Questions (FAQ)](https://github.com/IgorMundstein/WinMemoryCleaner?tab=readme-ov-file#why-has-the-app-been-flagged-as-a-virustrojan-and-blocked-by-windows-defender-or-antivirus)
