### ISSUE TITLE
Virus Trojan Windows 10 

### ISSUE THREAD

**Issue by Immersiiv** [IgorMundstein/WinMemoryCleaner#68]
### Checklist

- [X] I have used the search function to see if someone else has submitted the same bug report.
- [X] I will describe the problem in as much detail as possible.

### App version

2.6

### Windows version

Windows 10 (Win32)

### Steps To Reproduce

After two days of almost constant use
I started up my computer, and the "WinMemoryCleaner" application asked me to grant it administration rights on my computer, 
Thinking it was normal, I gave it the rights, and a few seconds later,

Windows Antivirus detected a "Trojan:Win32" after automatically launching the application

### Current Behavior

Live with antivirus and Windows security activated to remove and eliminate the problem :(

### Anything else?

![IMG_20231218_173318](https://github.com/IgorMundstein/WinMemoryCleaner/assets/147830106/ca2ceb80-3321-4a52-a59b-7f096752afad)

(ps : It's in French, but "Cheval de Troie" is Trojan virus)

**Comment by IgorMundstein** [comment]
### That's a common issue that persists every time a new app version is released. I constantly submit the executable to Microsoft. Usually, it takes 24 hours to 48 hours for Microsoft to remove the detection.

Meanwhile, you can follow this procedure.
https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

The app adds entries to the registry and task scheduler to run the app on startup. Windows doesn't "like" apps with admin privileges running on startup. I get that, but this is the way to do it. I apologize, but the app can not deep clean the memory without admin privileges.

It helps if more users submit the app to Microsoft analysis.
https://www.microsoft.com/en-us/wdsi/filesubmission

![Untitled](https://github.com/IgorMundstein/WinMemoryCleaner/assets/3512138/63cc4a50-6b2f-4b0b-88d2-7f5a7a106630)

### Microsoft feedback e-mail

> At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.
> 
> Open the command prompt as administrator.
> 
> 1. cd "c:\Program Files\Windows Defender"
> 2. MpCmdRun.exe -removedefinitions -dynamicsignatures
> 3. MpCmdRun.exe -SignatureUpdate

![image](https://github.com/IgorMundstein/WinMemoryCleaner/assets/3512138/bfb35128-9868-48e0-9f79-96619695a455)

### Similar reports

- [Bitdefender Flagged and Removed the .exe](https://github.com/IgorMundstein/WinMemoryCleaner/issues/48)
- [Flagged as malware by Windows](https://github.com/IgorMundstein/WinMemoryCleaner/discussions/45)

**Comment by IgorMundstein** [comment]
Added to [Frequently Asked Questions (FAQ)](https://github.com/IgorMundstein/WinMemoryCleaner?tab=readme-ov-file#why-has-the-app-been-flagged-as-a-virustrojan-and-blocked-by-windows-defender-or-antivirus)
