### ISSUE TITLE
Optimize by clicking the tray icon

### ISSUE THREAD

**Issue by z1nc0r3** [IgorMundstein/WinMemoryCleaner#78]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem in as much detail as possible.
- [X] This issue only requests one feature, **not** multiple (related) features.

### App version

2.8

### Problem you are trying to solve

I have been using [memreduct](https://github.com/henrypp/memreduct) for a while now and thought of trying something new and found this one. The memreduct has implemented a feature that we can double-click on the system tray icon to optimize the memory without opening the application. That is indeed easy and saves some extra clicks. I have checked the documentation but couldn't find this feature.

### Suggested solution

Integrate the memory optimization process directly to the system tray icon so users can just double-click (or single-click - customizable) to run the optimization.

**Comment by IgorMundstein** [comment]
Yeah, so this program is like an alternative to MemReduc. I used to use MemReduc, but the developer seemed kinda impatient and arrogant when I read the conversations he had with other users. So, I decided to make an app that's just as good or even better.

About your request, I'll have to think about it. The default setting is that a single mouse click shows and hides the program, and I don't plan on changing that. MemReduc lets you customize these mouse events, but it also has a bug with the middle mouse button on Windows 11. Windows can be a pain regarding specific customizations, and I don't want to add bugs to the app.

By the way, did you know you can set a keyboard hotkey to run the optimization process? It's even faster than double-clicking that tiny icon in the corner of the window. I know some people aren't used to keyboard shortcuts, but they can be handy once you get the hang of them.

**Comment by z1nc0r3** [comment]
Hello, thank you for taking the time to provide me with a detailed reply. Regarding the bug, I believe it's best to leave it as it is then. Thanks for mentioning the keyboard shortcuts as I use them regularly, and wasn't aware of it before.
