### ISSUE TITLE
[Feature] More details on tray icon mouse hover

### ISSUE THREAD

**Issue by realgooseman** [IgorMundstein/WinMemoryCleaner#79]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem in as much detail as possible.
- [X] This issue only requests one feature, **not** multiple (related) features.

### App version

2.8

### Problem you are trying to solve

Seeing more details on tray icon mouse hover.

### Suggested solution

Hi, I would like to suggest a new feature.

What would be useful (at least for me) is to add more details when hovering your mouse on the tray icon.

For now, when hovering you only see the "used memory" percentage. It would be nice to add the "free memory" percentage as well as the GB used next to these percentages.

And remove the capitalized "MEMORY USAGE" text to keep it even more cleaner.

**Comment by IgorMundstein** [comment]
It is not advisable to overload this area with excessive information, as it is a compact space with limited display capacity. If you choose to display virtual memory, there will already be three lines, and depending on the size, Windows may break the line, making the information challenging to comprehend. The memory usage label serves to clarify the type of percentage being displayed. Without it, confusion may arise.
