### ISSUE TITLE
Automating until v2.0 comes out

### ISSUE THREAD

**Issue by mountaser** [IgorMundstein/WinMemoryCleaner#8]
#  Quick way to automate this until v2.0 with automation comes out:

i downloaded the WinMemoryCleaner.exe and placed it under "C:\Program Files\WinMemoryCleaner" and created a script called run.ps1 in the same folder as well with the follwing code:

 `Start-Process -FilePath "C:\Program Files\WinMemoryCleaner\WinMemoryCleaner.exe" -ArgumentList "/CombinedPageList","/ModifiedPageList","/ProcessesWorkingSet","/StandbyList","/StandbyListLowPriority","/SystemWorkingSet" -WindowStyle Hidden` 

i have all arguments listed remove the ones you dont want.

you can put it anywhere you want just adjust the path in step 5 if you want to place it somewhere else

Now do the following:

1) Open Task Scheduler: You can open Task Scheduler by searching for it in the Start menu or by pressing Windows + R on your keyboard, typing "taskschd.msc" into the Run dialog box, and pressing Enter.

2) Create a new task: In the Task Scheduler window, click on "Create Task" in the right-hand pane to start creating a new task.

3) Name and configure the task: In the "General" tab of the "Create Task" dialog box, give your task a name that describes what it does. Under "Security options," make sure that "Run whether user is logged on or not" is selected, and check the box for "Run with highest privileges" if your script requires administrative permissions to run.

4) Schedule the task: In the "Triggers" tab, click on "New" to add a new trigger. Here, you can set up when and how often your task will run. Select "Daily" as the trigger type, and set the "Recur every" value to 1 days. Under "Advanced settings," select "Repeat task every" and set the value to 30 minutes. Set the start time to the time when you want the task to start running, and set the end time to a date far in the future to ensure that the task will continue to run indefinitely.

5) Add an action: In the "Actions" tab, click on "New" to add a new action. Here, select "Start a program" as the action type, and in the  "Program/script" field type "PowerShell.exe".
In the "Add arguments" field, enter the following 
`-ExecutionPolicy Bypass -File "C:\Program Files\WinMemoryCleaner\run.ps1" -NonInteractive` 

6) Save the task: Once you've configured all the settings for your task, click on "OK" to save it. You may be prompted to enter your username and password if your task requires administrative privileges to run.

#4
#6
#5 

![image](https://user-images.githubusercontent.com/17933154/221075535-39afdfd7-9d7b-4904-9c71-e155103ddc04.png)
![image](https://user-images.githubusercontent.com/17933154/221075582-2282eab0-c09f-42bf-9351-5878f34b6faf.png)
![image](https://user-images.githubusercontent.com/17933154/221075660-ca274f27-7372-4464-84fb-191d1a62a742.png)

for fun i made chatGPT write a ps1 script that does all of the above but didnt test it so you have fun with it 

```

# Set parameters
$downloadUrl = "https://github.com/IgorMundstein/WinMemoryCleaner/releases/download/1.1/WinMemoryCleaner.exe"
$executablePath = "C:\Program Files\WinMemoryCleaner\WinMemoryCleaner.exe"
$arguments = "/CombinedPageList /ModifiedPageList /ProcessesWorkingSet /StandbyList /StandbyListLowPriority /SystemWorkingSet"
$taskName = "WinMemoryCleaner"
$taskDescription = "Automatically runs WinMemoryCleaner every 30 minutes"
$taskPath = "\Microsoft\Windows\WinMemoryCleaner"
$taskInterval = New-TimeSpan -Minutes 30

# Create directory for executable
$directoryPath = "C:\Program Files\WinMemoryCleaner"
if (!(Test-Path $directoryPath)) {
    New-Item -ItemType Directory -Path $directoryPath | Out-Null
}

# Download executable
$webClient = New-Object System.Net.WebClient
$webClient.DownloadFile($downloadUrl, $executablePath)

# Create script to run executable
$scriptPath = "C:\Program Files\WinMemoryCleaner\run.ps1"
$scriptContent = "@echo off`n&`"" + $executablePath + "`" " + $arguments
$scriptContent | Out-File $scriptPath -Encoding ASCII

# Create task to run executable every 30 minutes
$action = New-ScheduledTaskAction -Execute "PowerShell.exe" -Argument "-NoProfile -WindowStyle Hidden -Command `"& 'C:\Program Files\WinMemoryCleaner\run.ps1'`""
$trigger = New-ScheduledTaskTrigger -Once -At (Get-Date) -RepetitionInterval $taskInterval -RepetitionDuration ([TimeSpan]::MaxValue)
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -RunOnlyIfNetworkAvailable -DontStopOnIdleEnd -WakeToRun
Register-ScheduledTask -TaskName $taskName -Description $taskDescription -Action $action -Trigger $trigger -Settings $settings -User "SYSTEM"

# Enable task to run on demand
$task = Get-ScheduledTask -TaskPath $taskPath -TaskName $taskName
$taskSettings = $task.Settings
$taskSettings.RunOnlyIfIdle = $false
$taskSettings.DisallowStartIfOnBatteries = $false
$task.Settings = $taskSettings
Set-ScheduledTask -TaskPath $taskPath -TaskName $taskName -Settings $taskSettings

# Run the task
Start-ScheduledTask -TaskPath $taskPath -TaskName $taskName

```

chatGPT quote: 

> This script will download the WinMemoryCleaner.exe file from the given URL and save it to C:\Program Files\WinMemoryCleaner\WinMemoryCleaner.exe. It will also create the run.ps1 script that runs the executable with the given arguments. Finally, it creates a scheduled task that runs the run.ps1 script every 30 minutes as the SYSTEM user.
> 
> Note that you should run this script with elevated privileges in order to create the directory and files in the C:\Program Files\ directory. Also, make sure that the URL for the WinMemoryCleaner.exe file is still valid before running

**Comment by IgorMundstein** [comment]
Nice work @mountaser 

I was unsure if someone was using the app. Glad to know it's been helpful.

**Comment by mountaser** [comment]
@IgorMundstein thanks.
yah its a grate tool. having only 16gb of ram on windows 11 isnt enough anymore xD 
ps: kudos on making the tool run in silent mode xD automating it wouldnt be possible if you didnt make that design decision

**Comment by IgorMundstein** [comment]
> @IgorMundstein thanks. yah its a grate tool. having only 16gb of ram on windows 11 isnt enough anymore xD ps: kudos on making the tool run in silent mode xD automating it wouldnt be possible if you didnt make that design decision

I feel the pain. Unfortunately, even with more memory, windows still need to handle it better. If you let your PC on for a week, you will feel it. It might look simple, but you are developing your PowerShell and chatGPT skills. Keep up the good work.

The initial goal of my app is to keep it simple because if you already have memory issues, you don't want one more application consuming more resources. That's why it is limited to a simple UI and lacks other features. The fact it runs on old windows versions also makes it harder to upgrade some stuff because I have to use a discontinued .NET Framework. 

Anyway, people's posts about updates incentivize me to keep working on it. I'll dedicate some time to it in the following weeks.

**Comment by ShatteredGod** [comment]
nice thank you for this!

**Comment by IgorMundstein** [comment]
Added.

Download the new version: https://github.com/IgorMundstein/WinMemoryCleaner/releases/latest/download/WinMemoryCleaner.exe
